name: Sync Backend ke Mirror

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode dari repo utama
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push HANYA folder backend ke repo mirror
        run: |
          # Potong folder 'backend' dan jadikan branch sementara bernama 'backend-only'
          git subtree split --prefix=backend -b backend-only
          
          # Push branch sementara tersebut ke repo mirror
          #git push https://wanna-beyours:${{ secrets.MIRROR_TOKEN }}@github.com/wanna-beyours/backend.git backend-only:main --force
          git push https://${{ secrets.MIRROR_TOKEN }}@github.com/wanna-beyours/backend.git backend-only:main --force
